version: '2'

services:

  elasticsearch:
    build: elasticsearch/
    environment: 
      ES_JAVA_OPTS: "-Xmx4g -Xms4g" 
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  logstash:
    build: logstash/
    networks:
      - localdev
  
  kibana:
    build: kibana/

networks:
  localdev:
    external: true
