## Filebeat configuration
## https://github.com/elastic/beats/blob/main/deploy/docker/filebeat.docker.yml
#

name: filebeat

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    # The Docker autodiscover provider automatically retrieves logs from Docker
    # containers as they start and stop.
    - type: docker
      hints.enabled: true

processors:
  - add_cloud_metadata: ~

monitoring:
  enabled: true
  elasticsearch:
    username: beats_system
    password: ${BEATS_SYSTEM_PASSWORD}

output.elasticsearch:
  hosts: [ https://elasticsearch:9200 ]
  username: filebeat_internal
  password: ${FILEBEAT_INTERNAL_PASSWORD}
  ssl:
    # Using ${path.home} here while monitoring is enabled causes Beats to exit with:
    #   missing field accessing 'ssl.certificate_authorities.0'
    certificate_authorities: [ /usr/share/filebeat/ca.crt ]

## HTTP endpoint for health checking
## https://www.elastic.co/guide/en/beats/filebeat/current/http-endpoint.html
#

http:
  enabled: true
  host: 0.0.0.0
