# https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/otlpreceiver/README.md

receivers:
  otlp:
    protocols:
      # grpc:
      http:

exporters:
  logging:
    loglevel: warn 
  otlp/elastic: 
    # Elastic APM server https endpoint without the "https://" prefix
    endpoint: http://127.0.0.1:8200
    tls:
        insecure: true
        insecure_skip_verify: true
    compression: none
    # headers:
    #   # Elastic APM Server secret token
    #   Authorization: "Bearer ${ELASTIC_APM_SECRET_TOKEN}"  


service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]
    metrics:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]
    logs: 
      receivers: [otlp]
      exporters: [logging, otlp/elastic]



# receivers: 
#   otlp:
#     protocols:
#       grpc:

# processors: 
#   # ...
#   memory_limiter:
#     check_interval: 1s
#     limit_mib: 2000
#   batch:

# exporters:
#   logging:
#     loglevel: warn 
#   otlp/elastic: 
#     # Elastic APM server https endpoint without the "https://" prefix
#     endpoint: "localhost:8200"
#     # headers:
#     #   # Elastic APM Server secret token
#     #   Authorization: "Bearer ${ELASTIC_APM_SECRET_TOKEN}"  

# service:
#   pipelines:
#     traces:
#       receivers: [otlp]
#       exporters: [logging, otlp/elastic]
#     metrics:
#       receivers: [otlp]
#       exporters: [logging, otlp/elastic]
#     logs: 
#       receivers: [otlp]
#       exporters: [logging, otlp/elastic]
