---
## Default Logstash configuration from logstash-docker.
## from https://github.com/elastic/logstash-docker/blob/master/build/logstash/config/logstash.yml
#
http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline

#  Uncomment when we buy XPACK
# xpack.monitoring.elasticsearch.url: ["elasticsearch:9200"] 
# xpack.monitoring.elasticsearch.username: "logstash_system"
# xpack.monitoring.elasticsearch.password: changeme

## Delete this when we buy XPACK
## Disable X-Pack 
## see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html 
##     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling 
# 
xpack.monitoring.enabled: false
